### ISSUE TITLE
Can't replicate backtest results Binance

### ISSUE THREAD

**Issue by Deleriumdelicious** [anakein/beastbotXB#1]
Hi anakein, 
I'm trying to replicate your backtest results on Binance with the same settings (pairs, time period, max_open_trades, starting balance...) but I get much less trades than the backtest result file that you uploaded for BeastBotXBLR7, see my results below. Freqtrade released in the mean time already some updates improving some backtest features, do you know if that could be the reason perhaps? 

Result for strategy BeastBotXBLR7
========================================================== BACKTESTING REPORT ==========================================================
|      Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|-----------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|  XRP/USDT |      3 |           3.28 |           9.84 |           197.093 |           4.93 |        1:48:00 |     3     0     0   100 |
| IOTA/USDT |      3 |           2.83 |           8.48 |           169.834 |           4.25 |        0:10:00 |     3     0     0   100 |
| ALGO/USDT |      5 |           1.64 |           8.22 |           164.496 |           4.11 |        2:04:00 |     4     0     1  80.0 |
|  ADA/USDT |      2 |           3.71 |           7.42 |           148.567 |           3.71 |        7:30:00 |     2     0     0   100 |
|  ETC/USDT |      2 |           2.69 |           5.38 |           107.765 |           2.69 |        0:05:00 |     2     0     0   100 |
|  SOL/USDT |      1 |           3.82 |           3.82 |            76.473 |           1.91 |        0:05:00 |     1     0     0   100 |
| AVAX/USDT |      1 |           1.61 |           1.61 |            32.170 |           0.80 |        0:05:00 |     1     0     0   100 |
|  TRX/USDT |      0 |           0.00 |           0.00 |             0.000 |           0.00 |           0:00 |     0     0     0     0 |
|  BTC/USDT |      0 |           0.00 |           0.00 |             0.000 |           0.00 |           0:00 |     0     0     0     0 |
|  BCH/USDT |      1 |          -9.19 |          -9.19 |          -183.936 |          -4.60 |        0:05:00 |     0     0     1     0 |
|     TOTAL |     18 |           1.98 |          35.59 |           712.462 |          17.81 |        1:46:00 |    16     0     2  88.9 |
============================================================ ENTER TAG STATS ============================================================
|        TAG |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|------------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
| Andalusian |      3 |           3.94 |          11.82 |           236.547 |           5.91 |        0:05:00 |     3     0     0   100 |
|       con8 |      4 |           2.24 |           8.96 |           179.419 |           4.49 |        7:02:00 |     4     0     0   100 |
|       con1 |      6 |           0.96 |           5.77 |           115.469 |           2.89 |        0:06:00 |     5     0     1  83.3 |
|       con3 |      2 |           2.49 |           4.97 |            99.565 |           2.49 |        0:12:00 |     2     0     0   100 |
|       con9 |      2 |           2.13 |           4.27 |            85.462 |           2.14 |        0:10:00 |     2     0     0   100 |
|      trend |      1 |          -0.20 |          -0.20 |            -4.000 |          -0.10 |        1:55:00 |     0     0     1     0 |
|      TOTAL |     18 |           1.98 |          35.59 |           712.462 |          17.81 |        1:46:00 |    16     0     2  88.9 |
========================================================= EXIT REASON STATS ==========================================================
|            Exit Reason |   Exits |   Win  Draws  Loss  Win% |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |
|------------------------+---------+--------------------------+----------------+----------------+-------------------+----------------|
|          sf_1(  con1 ) |       3 |      3     0     0   100 |           3.53 |          10.58 |           211.731 |           2.64 |
|      sf_u_e_1(  con8 ) |       2 |      2     0     0   100 |           0.77 |           1.54 |            30.852 |           0.39 |
|          sf_0(  con1 ) |       2 |      2     0     0   100 |           2.19 |           4.38 |            87.674 |           1.09 |
|          sf_0(  con8 ) |       1 |      1     0     0   100 |           1.31 |           1.31 |            26.129 |           0.33 |
|          sf_0(  con9 ) |       1 |      1     0     0   100 |           1.61 |           1.61 |            32.17  |           0.4  |
|        sf_u_1(  con9 ) |       1 |      1     0     0   100 |           2.66 |           2.66 |            53.292 |           0.67 |
|             trend_stop |       1 |      0     0     1     0 |          -0.2  |          -0.2  |            -4     |          -0.05 |
|   sf_1(  Andalusian  ) |       1 |      1     0     0   100 |           3.8  |           3.8  |            76.107 |           0.95 |
|   sf_2(  Andalusian  ) |       1 |      1     0     0   100 |           5.88 |           5.88 |           117.664 |           1.47 |
| sf_u_1(  Andalusian  ) |       1 |      1     0     0   100 |           2.14 |           2.14 |            42.776 |           0.53 |
|    stoploss8 (  con1 ) |       1 |      0     0     1     0 |          -9.19 |          -9.19 |          -183.936 |          -2.3  |
|          sf_0(  con3 ) |       1 |      1     0     0   100 |           2.08 |           2.08 |            41.715 |           0.52 |
|          sf_2(  con8 ) |       1 |      1     0     0   100 |           6.12 |           6.12 |           122.438 |           1.53 |
|        sf_u_1(  con3 ) |       1 |      1     0     0   100 |           2.89 |           2.89 |            57.85  |           0.72 |
====================================================== LEFT OPEN TRADES REPORT ======================================================
|   Pair |   Buys |   Avg Profit % |   Cum Profit % |   Tot Profit USDT |   Tot Profit % |   Avg Duration |   Win  Draw  Loss  Win% |
|--------+--------+----------------+----------------+-------------------+----------------+----------------+-------------------------|
|  TOTAL |      0 |           0.00 |           0.00 |             0.000 |           0.00 |           0:00 |     0     0     0     0 |
======================== DAY BREAKDOWN =========================
|        Day |   Tot Profit USDT |   Wins |   Draws |   Losses |
|------------+-------------------+--------+---------+----------|
| 25/09/2021 |            26.129 |      1 |       0 |        0 |
| 26/09/2021 |             0     |      0 |       0 |        0 |
| 27/09/2021 |             0     |      0 |       0 |        0 |
| 28/09/2021 |             0     |      0 |       0 |        0 |
| 29/09/2021 |             0     |      0 |       0 |        0 |
| 30/09/2021 |             0     |      0 |       0 |        0 |
| 01/10/2021 |             0     |      0 |       0 |        0 |
| 02/10/2021 |             0     |      0 |       0 |        0 |
| 03/10/2021 |             0     |      0 |       0 |        0 |
| 04/10/2021 |             0     |      0 |       0 |        0 |
| 05/10/2021 |             0     |      0 |       0 |        0 |
| 06/10/2021 |             0     |      0 |       0 |        0 |
| 07/10/2021 |             0     |      0 |       0 |        0 |
| 08/10/2021 |             0     |      0 |       0 |        0 |
| 09/10/2021 |             0     |      0 |       0 |        0 |
| 10/10/2021 |             0     |      0 |       0 |        0 |
| 11/10/2021 |             0     |      0 |       0 |        0 |
| 12/10/2021 |             0     |      0 |       0 |        0 |
| 13/10/2021 |             0     |      0 |       0 |        0 |
| 14/10/2021 |             0     |      0 |       0 |        0 |
| 15/10/2021 |             0     |      0 |       0 |        0 |
| 16/10/2021 |             0     |      0 |       0 |        0 |
| 17/10/2021 |             0     |      0 |       0 |        0 |
| 18/10/2021 |             0     |      0 |       0 |        0 |
| 19/10/2021 |             0     |      0 |       0 |        0 |
| 20/10/2021 |             0     |      0 |       0 |        0 |
| 21/10/2021 |             0     |      0 |       0 |        0 |
| 22/10/2021 |             0     |      0 |       0 |        0 |
| 23/10/2021 |             0     |      0 |       0 |        0 |
| 24/10/2021 |             0     |      0 |       0 |        0 |
| 25/10/2021 |             0     |      0 |       0 |        0 |
| 26/10/2021 |             0     |      0 |       0 |        0 |
| 27/10/2021 |           155.731 |      3 |       0 |        0 |
| 28/10/2021 |             0     |      0 |       0 |        0 |
| 29/10/2021 |             0     |      0 |       0 |        0 |
| 30/10/2021 |             0     |      0 |       0 |        0 |
| 31/10/2021 |             0     |      0 |       0 |        0 |
| 01/11/2021 |             0     |      0 |       0 |        0 |
| 02/11/2021 |            -4     |      0 |       0 |        1 |
| 03/11/2021 |             0     |      0 |       0 |        0 |
| 04/11/2021 |             0     |      0 |       0 |        0 |
| 05/11/2021 |             0     |      0 |       0 |        0 |
| 06/11/2021 |             0     |      0 |       0 |        0 |
| 07/11/2021 |             0     |      0 |       0 |        0 |
| 08/11/2021 |             0     |      0 |       0 |        0 |
| 09/11/2021 |             0     |      0 |       0 |        0 |
| 10/11/2021 |           236.547 |      3 |       0 |        0 |
| 11/11/2021 |            30.852 |      2 |       0 |        0 |
| 12/11/2021 |             0     |      0 |       0 |        0 |
| 13/11/2021 |             0     |      0 |       0 |        0 |
| 14/11/2021 |             0     |      0 |       0 |        0 |
| 15/11/2021 |             0     |      0 |       0 |        0 |
| 16/11/2021 |             0     |      0 |       0 |        0 |
| 17/11/2021 |             0     |      0 |       0 |        0 |
| 18/11/2021 |             0     |      0 |       0 |        0 |
| 19/11/2021 |             0     |      0 |       0 |        0 |
| 20/11/2021 |             0     |      0 |       0 |        0 |
| 21/11/2021 |             0     |      0 |       0 |        0 |
| 22/11/2021 |             0     |      0 |       0 |        0 |
| 23/11/2021 |             0     |      0 |       0 |        0 |
| 24/11/2021 |             0     |      0 |       0 |        0 |
| 25/11/2021 |             0     |      0 |       0 |        0 |
| 26/11/2021 |             0     |      0 |       0 |        0 |
| 27/11/2021 |             0     |      0 |       0 |        0 |
| 28/11/2021 |             0     |      0 |       0 |        0 |
| 29/11/2021 |             0     |      0 |       0 |        0 |
| 30/11/2021 |             0     |      0 |       0 |        0 |
| 01/12/2021 |             0     |      0 |       0 |        0 |
| 02/12/2021 |             0     |      0 |       0 |        0 |
| 03/12/2021 |             0     |      0 |       0 |        0 |
| 04/12/2021 |            10.442 |      4 |       0 |        1 |
| 05/12/2021 |             0     |      0 |       0 |        0 |
| 06/12/2021 |             0     |      0 |       0 |        0 |
| 07/12/2021 |             0     |      0 |       0 |        0 |
| 08/12/2021 |             0     |      0 |       0 |        0 |
| 09/12/2021 |             0     |      0 |       0 |        0 |
| 10/12/2021 |             0     |      0 |       0 |        0 |
| 11/12/2021 |             0     |      0 |       0 |        0 |
| 12/12/2021 |             0     |      0 |       0 |        0 |
| 13/12/2021 |             0     |      0 |       0 |        0 |
| 14/12/2021 |             0     |      0 |       0 |        0 |
| 15/12/2021 |             0     |      0 |       0 |        0 |
| 16/12/2021 |             0     |      0 |       0 |        0 |
| 17/12/2021 |             0     |      0 |       0 |        0 |
| 18/12/2021 |             0     |      0 |       0 |        0 |
| 19/12/2021 |             0     |      0 |       0 |        0 |
| 20/12/2021 |             0     |      0 |       0 |        0 |
| 21/12/2021 |             0     |      0 |       0 |        0 |
| 22/12/2021 |             0     |      0 |       0 |        0 |
| 23/12/2021 |             0     |      0 |       0 |        0 |
| 24/12/2021 |             0     |      0 |       0 |        0 |
| 25/12/2021 |             0     |      0 |       0 |        0 |
| 26/12/2021 |             0     |      0 |       0 |        0 |
| 27/12/2021 |             0     |      0 |       0 |        0 |
| 28/12/2021 |             0     |      0 |       0 |        0 |
| 29/12/2021 |             0     |      0 |       0 |        0 |
| 30/12/2021 |             0     |      0 |       0 |        0 |
| 31/12/2021 |             0     |      0 |       0 |        0 |
| 01/01/2022 |             0     |      0 |       0 |        0 |
| 02/01/2022 |             0     |      0 |       0 |        0 |
| 03/01/2022 |             0     |      0 |       0 |        0 |
| 04/01/2022 |             0     |      0 |       0 |        0 |
| 05/01/2022 |             0     |      0 |       0 |        0 |
| 06/01/2022 |             0     |      0 |       0 |        0 |
| 07/01/2022 |             0     |      0 |       0 |        0 |
| 08/01/2022 |             0     |      0 |       0 |        0 |
| 09/01/2022 |             0     |      0 |       0 |        0 |
| 10/01/2022 |             0     |      0 |       0 |        0 |
| 11/01/2022 |             0     |      0 |       0 |        0 |
| 12/01/2022 |             0     |      0 |       0 |        0 |
| 13/01/2022 |             0     |      0 |       0 |        0 |
| 14/01/2022 |             0     |      0 |       0 |        0 |
| 15/01/2022 |             0     |      0 |       0 |        0 |
| 16/01/2022 |             0     |      0 |       0 |        0 |
| 17/01/2022 |           122.438 |      1 |       0 |        0 |
| 18/01/2022 |             0     |      0 |       0 |        0 |
| 19/01/2022 |             0     |      0 |       0 |        0 |
| 20/01/2022 |             0     |      0 |       0 |        0 |
| 21/01/2022 |             0     |      0 |       0 |        0 |
| 22/01/2022 |           134.323 |      2 |       0 |        0 |
======================= MONTH BREAKDOWN ========================
|      Month |   Tot Profit USDT |   Wins |   Draws |   Losses |
|------------+-------------------+--------+---------+----------|
| 30/09/2021 |            26.129 |      1 |       0 |        0 |
| 31/10/2021 |           155.731 |      3 |       0 |        0 |
| 30/11/2021 |           263.399 |      5 |       0 |        1 |
| 31/12/2021 |            10.442 |      4 |       0 |        1 |
| 31/01/2022 |           256.761 |      3 |       0 |        0 |
=============== SUMMARY METRICS ================
| Metric                 | Value               |
|------------------------+---------------------|
| Backtesting from       | 2021-09-20 00:00:00 |
| Backtesting to         | 2022-01-27 00:00:00 |
| Max open trades        | 4                   |
|                        |                     |
| Total/Daily Avg Trades | 18 / 0.14           |
| Starting balance       | 4000 USDT           |
| Final balance          | 4712.462 USDT       |
| Absolute profit        | 712.462 USDT        |
| Total profit %         | 17.81%              |
| CAGR %                 | 59.01%              |
| Trades per day         | 0.14                |
| Avg. daily profit %    | 0.14%               |
| Avg. stake amount      | 2000 USDT           |
| Total trade volume     | 36000 USDT          |
|                        |                     |
| Best Pair              | XRP/USDT 9.84%      |
| Worst Pair             | BCH/USDT -9.19%     |
| Best trade             | ADA/USDT 6.12%      |
| Worst trade            | BCH/USDT -9.19%     |
| Best day               | 236.547 USDT        |
| Worst day              | -4 USDT             |
| Days win/draw/lose     | 7 / 112 / 1         |
| Avg. Duration Winners  | 1:51:00             |
| Avg. Duration Loser    | 1:00:00             |
| Rejected Entry signals | 0                   |
| Entry/Exit Timeouts    | 0 / 0               |
|                        |                     |
| Min balance            | 4026.129 USDT       |
| Max balance            | 4712.462 USDT       |
| Drawdown (Account)     | 4.03%               |
| Drawdown               | 183.936 USDT        |
| Drawdown high          | 559.039 USDT        |
| Drawdown low           | 375.103 USDT        |
| Drawdown Start         | 2021-12-04 05:10:00 |
| Drawdown End           | 2021-12-04 05:30:00 |
| Market change          | -43.17%             |
================================================

**Comment by anakein** [comment]
the version is outdated.

use the NWEv6 version, which has been tested in live and dry-run

**Comment by Deleriumdelicious** [comment]
Ok will try the new version. How come you deleted the previous Beastbot versions? Are they not working well anymore? Btw anakein, you are Fran right? This Alexander from telegram.
