### ISSUE TITLE
this won't work since your inf_tf is less than strategy timeframe

### ISSUE THREAD

**Issue by ShahAnuj2610** [anakein/beastbotXB#2]
https://github.com/anakein/beastbotXB/blob/5a6e21ea18a9747843c6cc4ffc8be574749dda56/working/NWEv6.py#L234

**Comment by anakein** [comment]
Is correct. BTC trend with timeframe 3m, only 1 time per cycle  all rest pairs 5m timeframe.
binance have 3m timeframe. and then, is working.

**Comment by anakein** [comment]
![Captura](https://user-images.githubusercontent.com/1563663/169626015-d607e44b-eda8-4e1a-8e28-500bcab9bfc4.PNG)

You can to see in chart bottom trend zone working
